name: ci-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  ci-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install rust stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Rust cache   
        uses: Swatinem/rust-cache@v2

      - name: Npm dependencies
        run: npm install

      - name: EsLint check
        run: npm run lintcheck

      - name: Type check
        run: npm run typecheck

      - name: Cargo fmt lib
        run: cargo fmt --manifest-path=packages/plugin/Cargo.toml --all -- --check

      - name:  Cargo clippy lib
        run: cargo clippy --manifest-path=packages/plugin/Cargo.toml --all-targets --all-features -- -D warnings
      
      - name: Cargo build lib
        run: cargo build --manifest-path=packages/plugin/Cargo.toml

      - name: Cargo fmt example-app
        run: cargo fmt --manifest-path=packages/examples/tauri-app/src-tauri/Cargo.toml --all -- --check

      - name: Cargo clippy example-app
        run: cargo clippy --manifest-path=packages/examples/tauri-app/src-tauri/Cargo.toml --all-targets --all-features -- -D warnings

      - name: Cargo build example-app
        run: cargo build --manifest-path=packages/examples/tauri-app/src-tauri/Cargo.toml